### ISSUE TITLE
make ignoring files

### ISSUE THREAD

**Issue by fgsoftware1** [fgsoftware1/wolfieOS#66]
make  all-recursive
make[1]: Entering directory '/home/fgygh/fgOS'
Making all in src
make[2]: Entering directory '/home/fgygh/fgOS/src'
Makefile:408: warning: overriding recipe for target '../build/bin/main.o'
Makefile:405: warning: ignoring old recipe for target '../build/bin/main.o'
Makefile:411: warning: overriding recipe for target '../build/bin/main.o'
Makefile:408: warning: ignoring old recipe for target '../build/bin/main.o'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/fgygh/fgOS/src'
make[2]: Entering directory '/home/fgygh/fgOS'
make[2]: Leaving directory '/home/fgygh/fgOS'
make[1]: Leaving directory '/home/fgygh/fgOS'

**Comment by circutrider21** [comment]
Did you fix it

**Comment by fgsoftware1** [comment]
> Did you fix it

yes

**Comment by fgsoftware1** [comment]
> Did you fix it

i don't no how

**Comment by fgsoftware1** [comment]
> Did you fix it

if you can look at this 
[repo](https://github.com/fgsoftware1/calculator-yacc-lex/issues/1)
